# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Soute < Formula
  desc "Zero-friction project file versioning"
  homepage "https://github.com/zachicecreamcohn/soute"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zachicecreamcohn/soute/releases/download/v0.1.0/soute_0.1.0_darwin_amd64.tar.gz"
      sha256 "8cf645bf0d31e724cd03a954ec3d93b1161c9c1d2e54576add3abe716d642582"

      define_method(:install) do
        bin.install "soute"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zachicecreamcohn/soute/releases/download/v0.1.0/soute_0.1.0_darwin_arm64.tar.gz"
      sha256 "061d5ca1d2f23aef96e638537759e423948939cfe3e2b3a0503da64af1cad401"

      define_method(:install) do
        bin.install "soute"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zachicecreamcohn/soute/releases/download/v0.1.0/soute_0.1.0_linux_amd64.tar.gz"
      sha256 "758def98effc4c62f7b7512b82520c6042bb16f1e31001c2329968cbf6fab9ec"
      define_method(:install) do
        bin.install "soute"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zachicecreamcohn/soute/releases/download/v0.1.0/soute_0.1.0_linux_arm64.tar.gz"
      sha256 "ebb868bffaa9fb8715215afa4228f3f9c8167ba77c5eaab274bf840158d69c4a"
      define_method(:install) do
        bin.install "soute"
      end
    end
  end
end
